version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - backend-net
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=gocl00!!
      - POSTGRES_USER=heachi
      - POSTGRES_DB=heachi
    networks:
      - backend-net

networks:
  backend-net: { }
