spring:
  application:
    name: heachi-backend
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: false
    hibernate:
      ddl-auto: update
  data:
    rest:
      max-page-size: 100
      default-page-size: 10
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
  jackson:
    default-property-inclusion: non-null
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/heachi
    username: heachi
    password: gocl00!!
ethereum:
  url: https://tn.henesis.io/ethereum/ropsten?clientId=815fcd01324b8f75818a755a72557750